# TF-IDF

In [1]:
import collections

In [2]:
#停用詞
stop_words=['\n', 'or', 'are', 'they', 'i', 'some', 'by', '—', 
            'even', 'the', 'to', 'a', 'and', 'of', 'in', 'on', 'for', 
            'that', 'with', 'is', 'as', 'could', 'its', 'this', 'other',
            'an', 'have', 'more', 'at','don’t', 'can', 'only', 'most']

In [9]:
!pip3 install scikit-learn

     ---------------------------------------- 0.0/59.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/59.0 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 59.0/59.0 kB 518.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.3 MB 1.3 MB/s eta 0:00:08
    --------------------------------------- 0.2/9.3 MB 2.3 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/9.3 MB 3.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.3 MB 5.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.3 MB 8.0 MB/s eta 0:00:01
   ------------- -------------------------- 3.2/9.3 MB 10.3 MB/s eta 0:00:01
   --------------- ------------------------ 3.7/9.3 MB 11.1 MB/s eta 0:00:01
   ----------------- ---------------------- 4.1/9.3 MB 10.1 MB/s eta 0:00:01
   ------------

In [10]:
# 載入相關套件
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

In [11]:
# 語料：最後一句為問題，其他為回答
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

In [13]:
# 將語料轉換為詞頻矩陣，計算各個字詞出現的次數。
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

# 生字表
word = vectorizer.get_feature_names_out()
print ("Vocabulary：", word)

Vocabulary： ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [14]:
# 查看四句話的 BOW
print ("BOW=\n", X.toarray())

BOW=
 [[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


In [15]:
# TF-IDF 轉換
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
print ("TF-IDF=\n", np.around(tfidf.toarray(), 4))

TF-IDF=
 [[0.     0.4388 0.542  0.4388 0.     0.     0.3587 0.     0.4388]
 [0.     0.2723 0.     0.2723 0.     0.8532 0.2226 0.     0.2723]
 [0.5528 0.     0.     0.     0.5528 0.     0.2885 0.5528 0.    ]
 [0.     0.4388 0.542  0.4388 0.     0.     0.3587 0.     0.4388]]


In [16]:
# 最後一句與其他句的相似度比較
from sklearn.metrics.pairwise import cosine_similarity
print (cosine_similarity(tfidf[-1], tfidf[:-1], dense_output=False))

  (0, 2)	0.1034849000930086
  (0, 1)	0.43830038447620107
  (0, 0)	1.0


# 字詞前處理

In [19]:
# 載入相關套件
import nltk

In [31]:
# 測試文章段落
text="Today is a great day. It is even better than yesterday." + \
     " And yesterday was the best day ever."


In [40]:
nltk.sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.']

In [28]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\basque_grammars.zip.
[nltk_data]   

True

In [32]:
# 分割字句
nltk.sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.']

In [33]:
# 分詞
nltk.word_tokenize(text)

['Today',
 'is',
 'a',
 'great',
 'day',
 '.',
 'It',
 'is',
 'even',
 'better',
 'than',
 'yesterday',
 '.',
 'And',
 'yesterday',
 'was',
 'the',
 'best',
 'day',
 'ever',
 '.']

In [34]:
#詞行還原
# 字根詞形還原(Stemming)
text = 'My system keeps crashing his crashed yesterday, ours crashes daily'
ps = nltk.porter.PorterStemmer()
' '.join([ps.stem(word) for word in text.split()])

'my system keep crash hi crash yesterday, our crash daili'

In [35]:
# 依字典規則的詞形還原(Lemmatization)
text = 'My system keeps crashing his crashed yesterday, ours crashes daily'
lem = nltk.WordNetLemmatizer()
' '.join([lem.lemmatize(word) for word in text.split()])

'My system keep crashing his crashed yesterday, ours crash daily'

# 停用詞

In [36]:
import string

In [37]:
print('標點符號:', string.punctuation)

標點符號: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [38]:
# 測試文章段落
text="Today is a great day. It is even better than yesterday." + \
     " And yesterday was the best day ever."

#讀取停用詞
stopword_list = set(nltk.corpus.stopwords.words('english') 
                    + list(string.punctuation))

In [39]:
# 移除停用詞(Removing Stopwords)
def remove_stopwords(text, is_lower_case=False):
    if is_lower_case:
        text = text.lower()
    tokens = nltk.word_tokenize(text)
    tokens = [token.strip() for token in tokens]
    filtered_tokens = [token for token in tokens if token not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)    
    return filtered_text, filtered_tokens

filtered_text, filtered_tokens = remove_stopwords(text) 
filtered_text

'Today great day It even better yesterday And yesterday best day ever'

# word2vec