# TF-IDF

In [1]:
import collections

In [2]:
#停用詞
stop_words=['\n', 'or', 'are', 'they', 'i', 'some', 'by', '—', 
            'even', 'the', 'to', 'a', 'and', 'of', 'in', 'on', 'for', 
            'that', 'with', 'is', 'as', 'could', 'its', 'this', 'other',
            'an', 'have', 'more', 'at','don’t', 'can', 'only', 'most']

In [9]:
!pip3 install scikit-learn

     ---------------------------------------- 0.0/59.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/59.0 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 59.0/59.0 kB 518.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.3 MB 1.3 MB/s eta 0:00:08
    --------------------------------------- 0.2/9.3 MB 2.3 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/9.3 MB 3.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.3 MB 5.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.3 MB 8.0 MB/s eta 0:00:01
   ------------- -------------------------- 3.2/9.3 MB 10.3 MB/s eta 0:00:01
   --------------- ------------------------ 3.7/9.3 MB 11.1 MB/s eta 0:00:01
   ----------------- ---------------------- 4.1/9.3 MB 10.1 MB/s eta 0:00:01
   ------------

In [10]:
# 載入相關套件
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

In [11]:
# 語料：最後一句為問題，其他為回答
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

In [13]:
# 將語料轉換為詞頻矩陣，計算各個字詞出現的次數。
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

# 生字表
word = vectorizer.get_feature_names_out()
print ("Vocabulary：", word)

Vocabulary： ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [14]:
# 查看四句話的 BOW
print ("BOW=\n", X.toarray())

BOW=
 [[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


In [15]:
# TF-IDF 轉換
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
print ("TF-IDF=\n", np.around(tfidf.toarray(), 4))

TF-IDF=
 [[0.     0.4388 0.542  0.4388 0.     0.     0.3587 0.     0.4388]
 [0.     0.2723 0.     0.2723 0.     0.8532 0.2226 0.     0.2723]
 [0.5528 0.     0.     0.     0.5528 0.     0.2885 0.5528 0.    ]
 [0.     0.4388 0.542  0.4388 0.     0.     0.3587 0.     0.4388]]


In [16]:
# 最後一句與其他句的相似度比較
from sklearn.metrics.pairwise import cosine_similarity
print (cosine_similarity(tfidf[-1], tfidf[:-1], dense_output=False))

  (0, 2)	0.1034849000930086
  (0, 1)	0.43830038447620107
  (0, 0)	1.0


# 字詞前處理

In [19]:
# 載入相關套件
import nltk

In [31]:
# 測試文章段落
text="Today is a great day. It is even better than yesterday." + \
     " And yesterday was the best day ever."


In [40]:
nltk.sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.']

In [28]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\88693\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\basque_grammars.zip.
[nltk_data]   

True

In [32]:
# 分割字句
nltk.sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.']

In [33]:
# 分詞
nltk.word_tokenize(text)

['Today',
 'is',
 'a',
 'great',
 'day',
 '.',
 'It',
 'is',
 'even',
 'better',
 'than',
 'yesterday',
 '.',
 'And',
 'yesterday',
 'was',
 'the',
 'best',
 'day',
 'ever',
 '.']

In [34]:
#詞行還原
# 字根詞形還原(Stemming)
text = 'My system keeps crashing his crashed yesterday, ours crashes daily'
ps = nltk.porter.PorterStemmer()
' '.join([ps.stem(word) for word in text.split()])

'my system keep crash hi crash yesterday, our crash daili'

In [35]:
# 依字典規則的詞形還原(Lemmatization)
text = 'My system keeps crashing his crashed yesterday, ours crashes daily'
lem = nltk.WordNetLemmatizer()
' '.join([lem.lemmatize(word) for word in text.split()])

'My system keep crashing his crashed yesterday, ours crash daily'

# 停用詞

In [36]:
import string

In [37]:
print('標點符號:', string.punctuation)

標點符號: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [38]:
# 測試文章段落
text="Today is a great day. It is even better than yesterday." + \
     " And yesterday was the best day ever."

#讀取停用詞
stopword_list = set(nltk.corpus.stopwords.words('english') 
                    + list(string.punctuation))

In [39]:
# 移除停用詞(Removing Stopwords)
def remove_stopwords(text, is_lower_case=False):
    if is_lower_case:
        text = text.lower()
    tokens = nltk.word_tokenize(text)
    tokens = [token.strip() for token in tokens]
    filtered_tokens = [token for token in tokens if token not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)    
    return filtered_text, filtered_tokens

filtered_text, filtered_tokens = remove_stopwords(text) 
filtered_text

'Today great day It even better yesterday And yesterday best day ever'

# word2vec
* bow和TF_IDF都是計算文字出現在文件中的次數
* 這裡詞向量有兩個方法
1. CBOW-以上下文去預測單字
2. Continuos Skip-gram Model-以單字去預測上下文

In [1]:
!pip3 install gensim

   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.0 MB 1.3 MB/s eta 0:00:19
   ---------------------------------------- 0.1/24.0 MB 1.1 MB/s eta 0:00:23
   ---------------------------------------- 0.2/24.0 MB 2.0 MB/s eta 0:00:13
    --------------------------------------- 0.5/24.0 MB 2.7 MB/s eta 0:00:09
   - -------------------------------------- 1.0/24.0 MB 4.4 MB/s eta 0:00:06
   --- ------------------------------------ 2.0/24.0 MB 7.2 MB/s eta 0:00:04
   ----- ---------------------------------- 3.1/24.0 MB 9.8 MB/s eta 0:00:03
   ----- ---------------------------------- 3.1/24.0 MB 9.8 MB/s eta 0:00:03
   ----- ---------------------------------- 3.1/24.0 MB 8.0 MB/s eta 0:00:03
   ------- -------------------------------- 4.7/24.0 MB 9.9 MB/s eta 0:00:02
   ----------- ---------------------------- 6.8/24.0 MB 13.2 MB/s eta 0:00:02
   -------------- ------------------------- 8.5/24.0 MB 15.0 MB/s eta 0:00:02
   -

In [2]:
# 載入相關套件
import pprint  # 較美觀的列印函數
import gensim
from collections import defaultdict
from gensim import corpora

In [3]:
# 語料庫
documents = [
    "Human machine interface for lab abc computer applications",
    "A survey of user opinion of computer system response time",
    "The EPS user interface management system",
    "System and human system engineering testing of EPS",
    "Relation of user perceived response time to error measurement",
    "The generation of random binary unordered trees",
    "The intersection graph of paths in trees",
    "Graph minors IV Widths of trees and well quasi ordering",
    "Graph minors A survey",
]

In [9]:
stoplist = set('for a of the and to in'.split()) #停用詞

texts = [[word for word in document.lower().split() if word not in stoplist] for document in documents] #轉小寫並將停用詞刪除

texts

[['human', 'machine', 'interface', 'lab', 'abc', 'computer', 'applications'],
 ['survey', 'user', 'opinion', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'management', 'system'],
 ['system', 'human', 'system', 'engineering', 'testing', 'eps'],
 ['relation', 'user', 'perceived', 'response', 'time', 'error', 'measurement'],
 ['generation', 'random', 'binary', 'unordered', 'trees'],
 ['intersection', 'graph', 'paths', 'trees'],
 ['graph', 'minors', 'iv', 'widths', 'trees', 'well', 'quasi', 'ordering'],
 ['graph', 'minors', 'survey']]

In [12]:
#單詞出現次數統計

frequency = defaultdict(int)

for text in texts:

    for token in text:

        frequency[token] += 1

In [13]:
frequency

defaultdict(int,
            {'human': 2,
             'machine': 1,
             'interface': 2,
             'lab': 1,
             'abc': 1,
             'computer': 2,
             'applications': 1,
             'survey': 2,
             'user': 3,
             'opinion': 1,
             'system': 4,
             'response': 2,
             'time': 2,
             'eps': 2,
             'management': 1,
             'engineering': 1,
             'testing': 1,
             'relation': 1,
             'perceived': 1,
             'error': 1,
             'measurement': 1,
             'generation': 1,
             'random': 1,
             'binary': 1,
             'unordered': 1,
             'trees': 3,
             'intersection': 1,
             'graph': 3,
             'paths': 1,
             'minors': 2,
             'iv': 1,
             'widths': 1,
             'well': 1,
             'quasi': 1,
             'ordering': 1})

In [14]:
texts = [
    [token for token in text if frequency[token] > 1]
    for text in texts
]
texts

[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey']]

In [15]:
# 轉為字典
dictionary = corpora.Dictionary(texts)

# 轉為 BOW
corpus = [dictionary.doc2bow(text) for text in texts]
corpus

[[(0, 1), (1, 1), (2, 1)],
 [(0, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)],
 [(2, 1), (5, 1), (7, 1), (8, 1)],
 [(1, 1), (5, 2), (8, 1)],
 [(3, 1), (6, 1), (7, 1)],
 [(9, 1)],
 [(9, 1), (10, 1)],
 [(9, 1), (10, 1), (11, 1)],
 [(4, 1), (10, 1), (11, 1)]]

## 建立LSI模型

In [17]:
# 建立 LSI (Latent semantic indexing) 模型
from gensim import models

# num_topics=2：取二維，即兩個議題
lsi = models.LsiModel(corpus, id2word=dictionary, num_topics=2)

# 兩個議題的 LSI 公式
lsi.print_topics(2)

[(0,
  '0.644*"system" + 0.404*"user" + 0.301*"eps" + 0.265*"response" + 0.265*"time" + 0.240*"computer" + 0.221*"human" + 0.206*"survey" + 0.198*"interface" + 0.036*"graph"'),
 (1,
  '0.623*"graph" + 0.490*"trees" + 0.451*"minors" + 0.274*"survey" + -0.167*"system" + -0.141*"eps" + -0.113*"human" + 0.107*"response" + 0.107*"time" + -0.072*"interface"')]

In [18]:
# 例句
doc = "Human computer interaction"

# 測試 LSI (Latent semantic indexing) 模型
vec_bow = dictionary.doc2bow(doc.lower().split())
vec_lsi = lsi[vec_bow]  
print(vec_lsi)

[(0, 0.46182100453271535), (1, -0.07002766527899937)]


In [19]:
# 比較例句與語料庫每一句的相似機率
from gensim import similarities
# 比較例句與語料庫的相似性索引
index = similarities.MatrixSimilarity(lsi[corpus])  
# 比較例句與語料庫的相似機率
sims = index[vec_lsi]  
# 顯示語料庫的索引值及相似機率
print(list(enumerate(sims)))  

[(0, 0.998093), (1, 0.93748635), (2, 0.9984453), (3, 0.9865886), (4, 0.90755945), (5, -0.12416792), (6, -0.10639259), (7, -0.09879464), (8, 0.050041765)]


In [20]:
# 依相似機率降冪排序
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for doc_position, doc_score in sims:
    print(doc_score, documents[doc_position])

0.9984453 The EPS user interface management system
0.998093 Human machine interface for lab abc computer applications
0.9865886 System and human system engineering testing of EPS
0.93748635 A survey of user opinion of computer system response time
0.90755945 Relation of user perceived response time to error measurement
0.050041765 Graph minors A survey
-0.09879464 Graph minors IV Widths of trees and well quasi ordering
-0.10639259 The intersection graph of paths in trees
-0.12416792 The generation of random binary unordered trees
